name: flora's CICD Workflow

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'

jobs:
  job1: 
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'HIGH'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx1
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: huruoqing/cicd:${{ github.sha }}

      - name: Digitally sign image
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: 'v2.1.1'

      - name: Send Slack Notification
        id: slack
        uses: rtCamp/action-slack-notify@v2
        env: 
          SLACK_TITLE: "Image built and signed"
          SLACK_MESSAGE: |
            Name: Huruoqing
            Matriculation: E1221827
            Email:huruoqing@qq.com
            GitHub: https://github.com/huruoqing/CICDproject10.git 
            Docker: https://hub.docker.com/repository/docker/huruoqing/dockerreoository/general
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          
      - name: Upload file to Slack
        uses: MeilCli/slack-upload-file@v3
        with:
          slack-token: ${{ secrets.SLACK_TOKEN }}
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'docs/*.txt'
          initial_comment: 'post by slack-upload-file' 


  
