name: flora's CICD Workflow

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'

jobs:
  job1: 
    if: ${{ vars.RUN == 'SUCCESS' && startsWith(github.event.head_commit.message, '#norun') != true }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          severity: 'CRITICAL'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx1
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: huruoqing/cicd:${{ github.sha }}

      - name: Digitally sign image
        uses: sigstore/cosign-installer@v2.2.0
        with:
          cosign-release: 'v2.2.0'

      - name: Sign image with a key
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
        env:
          TAGS: huruoqing/cicd:${{ github.sha }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}

      - name: Send Slack Notification
        id: slack
        uses: rtCamp/action-slack-notify@v2
        env: 
          SLACK_TITLE: "Image built and signed"
          SLACK_MESSAGE: |
            Name: Huruoqing
            Matriculation: A0286015H
            Email:E1221827@u.nus.edu
            GitHub: https://github.com/huruoqing/CICDproject10.git 
            Docker: https://hub.docker.com/repository/docker/huruoqing/dockerreoository/general
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          
  job2:
    if: ${{ vars.RUN == 'FAIL' && startsWith(github.event.head_commit.message, '#norun') != true }}
    runs-on: ubuntu-20.04

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'HIGH'

      - name: Send Slack notification2
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#FF0000'
          SLACK_TITLE: "Scan failed - huruoqing"
          SLACK_MESSAGE: |
            Failed trivy scan, see uploaded report
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Upload file to Slack2
        uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: 'trivy-results.txt'
          initial_comment: 'Scan report by Hu Ruoqing'

